// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rpcp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	RegisterUserGrpc(ctx context.Context, in *RegisterUserInput, opts ...grpc.CallOption) (*RegisterUserOutput, error)
	LoginGrpc(ctx context.Context, in *LoginInput, opts ...grpc.CallOption) (*LoginOutput, error)
	CheckEmailGrpc(ctx context.Context, in *CheckEmailInput, opts ...grpc.CallOption) (*CheckEmailOutput, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) RegisterUserGrpc(ctx context.Context, in *RegisterUserInput, opts ...grpc.CallOption) (*RegisterUserOutput, error) {
	out := new(RegisterUserOutput)
	err := c.cc.Invoke(ctx, "/UserService/RegisterUserGrpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) LoginGrpc(ctx context.Context, in *LoginInput, opts ...grpc.CallOption) (*LoginOutput, error) {
	out := new(LoginOutput)
	err := c.cc.Invoke(ctx, "/UserService/LoginGrpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CheckEmailGrpc(ctx context.Context, in *CheckEmailInput, opts ...grpc.CallOption) (*CheckEmailOutput, error) {
	out := new(CheckEmailOutput)
	err := c.cc.Invoke(ctx, "/UserService/CheckEmailGrpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	RegisterUserGrpc(context.Context, *RegisterUserInput) (*RegisterUserOutput, error)
	LoginGrpc(context.Context, *LoginInput) (*LoginOutput, error)
	CheckEmailGrpc(context.Context, *CheckEmailInput) (*CheckEmailOutput, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) RegisterUserGrpc(context.Context, *RegisterUserInput) (*RegisterUserOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUserGrpc not implemented")
}
func (UnimplementedUserServiceServer) LoginGrpc(context.Context, *LoginInput) (*LoginOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginGrpc not implemented")
}
func (UnimplementedUserServiceServer) CheckEmailGrpc(context.Context, *CheckEmailInput) (*CheckEmailOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckEmailGrpc not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_RegisterUserGrpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RegisterUserGrpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/RegisterUserGrpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RegisterUserGrpc(ctx, req.(*RegisterUserInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_LoginGrpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LoginGrpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/LoginGrpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LoginGrpc(ctx, req.(*LoginInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CheckEmailGrpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckEmailInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CheckEmailGrpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/CheckEmailGrpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CheckEmailGrpc(ctx, req.(*CheckEmailInput))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUserGrpc",
			Handler:    _UserService_RegisterUserGrpc_Handler,
		},
		{
			MethodName: "LoginGrpc",
			Handler:    _UserService_LoginGrpc_Handler,
		},
		{
			MethodName: "CheckEmailGrpc",
			Handler:    _UserService_CheckEmailGrpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
